name: live
author: ""
clients:
  live:
    runtime: node
  controller:
    runtime: browser
  live-blase:
    runtime: node
  phone:
    runtime: browser
    default: true
  public:
    runtime: browser
  midi_chords_sender:
    runtime: node
